// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from "flatbuffers"

export class LEntry {
  bb: flatbuffers.ByteBuffer | null = null
  bb_pos = 0
  __init(i: number, bb: flatbuffers.ByteBuffer): LEntry {
    this.bb_pos = i
    this.bb = bb
    return this
  }

  static getRootAsLEntry(bb: flatbuffers.ByteBuffer, obj?: LEntry): LEntry {
    return (obj || new LEntry()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb,
    )
  }

  static getSizePrefixedRootAsLEntry(
    bb: flatbuffers.ByteBuffer,
    obj?: LEntry,
  ): LEntry {
    bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH)
    return (obj || new LEntry()).__init(
      bb.readInt32(bb.position()) + bb.position(),
      bb,
    )
  }

  key(): string | null
  key(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null
  key(optionalEncoding?: any): string | Uint8Array | null {
    const offset = this.bb!.__offset(this.bb_pos, 4)
    return offset
      ? this.bb!.__string(this.bb_pos + offset, optionalEncoding)
      : null
  }

  value(): number {
    const offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0
  }

  static startLEntry(builder: flatbuffers.Builder) {
    builder.startObject(2)
  }

  static addKey(builder: flatbuffers.Builder, keyOffset: flatbuffers.Offset) {
    builder.addFieldOffset(0, keyOffset, 0)
  }

  static addValue(builder: flatbuffers.Builder, value: number) {
    builder.addFieldFloat64(1, value, 0.0)
  }

  static endLEntry(builder: flatbuffers.Builder): flatbuffers.Offset {
    const offset = builder.endObject()
    builder.requiredField(offset, 4) // key
    return offset
  }

  static createLEntry(
    builder: flatbuffers.Builder,
    keyOffset: flatbuffers.Offset,
    value: number,
  ): flatbuffers.Offset {
    LEntry.startLEntry(builder)
    LEntry.addKey(builder, keyOffset)
    LEntry.addValue(builder, value)
    return LEntry.endLEntry(builder)
  }
}
