// automatically generated by the FlatBuffers compiler, do not modify

export { CustomMap } from "./mypackage/custom-map.js"
export { MyModel } from "./mypackage/my-model.js"
export * as CustomMap_ from "./mypackage/custom-map-.js"
